#ifndef __INCLUDE_FENCING_CONSTANTS_H__
#define __INCLUDE_FENCING_CONSTANTS_H__

#define EPEE_DEPRESS_US 2000
#define EPEE_LOCKOUT_US 45000

#define FOIL_DEPRESS_US 14000
#define FOIL_LOCKOUT_US 300000

#define SABER_DEPRESS_US
#define SABER_LOCKOUT_US

#endif // #ifndef __INCLUDE_FENCING_CONSTANTS_H__
